# Tensor

## CRUD

### C

## 조회

In [3]:
import torch
points = torch.tensor([1.0, 2.0, 3.0, 4.0])

print(points[0])
print(float(points[0]))

tensor(1.)
1.0


## 사이즈 보기

In [14]:
import torch
x = torch.FloatTensor([
    [1,2],
    [2,3],
    [3,4]
])

print('x.size : ', x.size())
print('x.shape : ', x.shape)
print('x.dim: ', x.dim())
print('x.size(0): ', x.size(0))
print('x.size(1): ', x.size(1))
print('x.shape[1]: ', x.shape[1])

x.size :  torch.Size([3, 2])
x.shape :  torch.Size([3, 2])
x.dim:  2
x.size(0):  3
x.size(1):  2
x.shape[1]:  2


# pyTorch 기본사용법

## preprocess

In [ ]:
from __future__ import print_function
import torch

## 기본조작

초기화되지 않은 5*3 행렬 생성하기

In [ ]:
x = torch.empty(5,3)
print(x)

랜덤으로 초기화된 행렬 생성

In [ ]:
x = torch.rand(5,3)
print(x)

0으로 채워지고 logn 데이터 타입을 가지는 행렬 생성

In [ ]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

데이터로부터 직접 텐서 생성하기

In [ ]:
x = torch.tensor([5.5, 3])
print(x)

이미 존재하는 텐서를 기반으로 새로운 텐서 생성
입력센서의 속성(데이터 타입)들이 사용자에 의해 새롭게 제공되지 않는 이상 기존의 값 사용

In [ ]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

In [ ]:
x = torch.randn_like(x, dtype=torch.float) #override dtype
print(x)

생성한 텐서의 사이즈 확인

In [ ]:
print(x.size())

torch.Size는 파이썬의 자료형이기 때문에 튜플과 관련된 모든 연산을 지원

## 기본연산

### 더하기

In [ ]:
y = torch.rand(5,3)
print(x + y)

In [ ]:
x

In [ ]:
y

In [ ]:
## 더하기2
print(torch.add(x,y))

파라미터로 결과가 저장되는 결과 텐서(result) 지정

In [ ]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

#### 더하기(자체 inplace)

In [ ]:
# add x to y
y.add_(x)
print(y)

- 텐서를 제자리에서 변조하는 연산은 _문자를 이용하여 postfix(연산자를 피연산자의 뒷쪽에 표시)로 표기한다.
- 예를 들면 x.copy_(y)와 x.t_()는 x를 변경시킨다

## 인덱싱

- Numpy와 같은 표준 인덱싱

In [ ]:
print(x[:,1])

## 사이즈 변경

In [ ]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

- 1개의 요소를 가지는 텐서가 있으면 .item()을 이용하여 python에서 숫자 데이터처럼 값을 얻을 수 있음

In [ ]:
x = torch.randn(1)
print(x)

In [ ]:
print(x.item())

# 기타 사용법

## PIL 이미지를 numpy array로 변환

In [1]:
import numpy as np
from PIL import Image

img = Image.open('psdata/maemi.png')
img.show()

In [3]:
x = np.array(img)
print(x)
print(x.shape)

[[254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 ...
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]]
(428, 428)


In [4]:
x_2 = np.asarray(img)
print(x_2)
print(x_2.shape)

[[254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 ...
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]]
(428, 428)


## ndarray를 이미지로 변환

In [6]:
import numpy as np
from PIL import Image

img = Image.open('psdata/maemi.png')

x = np.array(img)
img2 = Image.fromarray(x)
img2.show()

img2.save('psdata/maemi2.png')

## torch tensor와 PIL image, numpy array 간의 변환

In [9]:
from torchvision.transforms import ToTensor, ToPILImage
from PIL import Image
import numpy as np


img_RGB  = Image.open('psdata/maemi.png').convert('RGB')
img_RGB_array  = np.array(img_RGB)

print(f'RGB  Image shape : {img_RGB_array.shape}')  # 428 x 428 x 3
print(f'RGB  Value Scale : {img_RGB_array.min()}~{img_RGB_array.max()}') # 0~255

# torchvision.transforms.ToTensor
tf_toTensor = ToTensor() 

# PIL to Tensor
img_RGB_tensor_from_PIL = tf_toTensor(img_RGB)

print(img_RGB_tensor_from_PIL)
print(img_RGB_tensor_from_PIL.size()) # 3 x 428 x 428
print(img_RGB_tensor_from_PIL.min(), img_RGB_tensor_from_PIL.max()) # 0~1


# Numpy array to Tensor
img_RGB_tensor_from_ndarray = tf_toTensor(img_RGB_array)

print(img_RGB_tensor_from_ndarray)
print(img_RGB_tensor_from_ndarray.size()) # 3 x 428 x 428
print(img_RGB_tensor_from_ndarray.min(), img_RGB_tensor_from_ndarray.max()) # 0~1


# torchvision.transforms.ToPILImage
tf_toPILImage = ToPILImage() 

img_PIL_from_Tensor = tf_toPILImage(img_RGB_tensor_from_PIL)

print(np.array(img_PIL_from_Tensor)) # 0~255
print(np.array(img_PIL_from_Tensor).shape) # 428 x 428 x 3


# Check values between numpy array and tensor
print(np.sum(~(img_RGB_array==np.array(img_PIL_from_Tensor)))) # 0 means all same

RGB  Image shape : (428, 428, 3)
RGB  Value Scale : 0~255
tensor([[[0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
         [0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
         [0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
         ...,
         [0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
         [0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
         [0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961]],

        [[0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
         [0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
         [0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
         ...,
         [0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
         [0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
         [0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961]],

        [[0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
         [0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],


# API

## torch.max

In [ ]:
import torch
import torch.nn as nn

data = torch.randint(10,(2,2))
print(data)
print(torch.max(data))

In [ ]:
import torch
import torch.nn as nn

data = torch.randint(10,(2,2))
print(data)
print(torch.max(data,1))